#!/usr/bin/env python3
"""gen-roadmap-pages.py — mirror the task tracker into the wiki (todo list).

Reads the SOURCE OF TRUTH — docs/index.html `taskData` + docs/progress.json — and
emits small, linked per-track roadmap pages into wiki/docs/roadmap/, plus an index
with live counts, plus the mkdocs nav block. So the wiki carries the todo list
(browsable by humans + local LLMs) without becoming a second source of truth: this
is GENERATED from progress.json, re-run after any tracker change.

Usage: python3 foss-setup/scripts/docs/gen-roadmap-pages.py
"""
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
HTML = REPO / "docs" / "index.html"
PROG = REPO / "docs" / "progress.json"
OUT = REPO / "wiki" / "docs" / "roadmap"
MKDOCS = REPO / "wiki" / "mkdocs.yml"

html = HTML.read_text(errors="replace")
i = html.index('[{"id":')
tasks, _ = json.JSONDecoder().raw_decode(html[i:])
prog = json.load(open(PROG))
done = {k for k, v in prog["done"].items() if v}
deferred = prog.get("deferred", {})
retired = prog.get("retired", {})


def status(tid):
    if tid in done:
        return "✅ done"
    if tid in retired:
        return "🗑️ retired"
    if tid in deferred:
        return "⏸️ deferred"
    return "⬜ open"


by_track = {}
for t in tasks:
    by_track.setdefault(t.get("track", "uncategorized"), []).append(t)

OUT.mkdir(parents=True, exist_ok=True)
for old in OUT.glob("*.md"):
    old.unlink()


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


for track, ts in sorted(by_track.items()):
    ts = sorted(ts, key=lambda x: x["id"])
    lines = [f"# Roadmap — {track}", "",
             f"{len(ts)} task(s). Status mirrors `docs/progress.json` (the source of truth).", "",
             "| Task | Title | Status | Effort |", "|---|---|---|---|"]
    for t in ts:
        title = t.get("title", "").replace("|", "\\|")
        lines.append(f"| `{t['id']}` | {title} | {status(t['id'])} | {t.get('estimate', '—')} |")
    lines += ["", "[← Roadmap overview](index.md)", ""]
    (OUT / f"{slug(track)}.md").write_text("\n".join(lines))

# index
total = len(tasks)
d = len(done & {t["id"] for t in tasks})
idx = ["# Roadmap (the todo list)", "",
       f"The full task tracker, mirrored from `docs/index.html` + `docs/progress.json` "
       f"(**the source of truth** — this page is generated by `scripts/docs/gen-roadmap-pages.py`).", "",
       f"**{d} / {total} done.** Browse by track:", "",
       "| Track | Tasks | Done | Open | Deferred | Retired |",
       "|---|---|---|---|---|---|"]
for track, ts in sorted(by_track.items()):
    ids = [t["id"] for t in ts]
    nd = sum(1 for x in ids if x in done)
    nr = sum(1 for x in ids if x in retired)
    ndf = sum(1 for x in ids if x in deferred and x not in done)
    no = len(ids) - nd - nr - ndf
    idx.append(f"| [{track}]({slug(track)}.md) | {len(ids)} | {nd} | {no} | {ndf} | {nr} |")
idx += ["", "**Legend:** ✅ done · ⬜ open · ⏸️ deferred · 🗑️ retired.",
        "See also: [Operations → Tracker](../operations/tracker.md) · [Hardware to buy](../reference/hardware.md).", ""]
(OUT / "index.md").write_text("\n".join(idx))

# nav
nav = ["      # BEGIN GENERATED ROADMAP NAV (managed by scripts/docs/gen-roadmap-pages.py)",
       "      - Overview: roadmap/index.md"]
for track in sorted(by_track):
    nav.append(f"      - {track}: roadmap/{slug(track)}.md")
nav.append("      # END GENERATED ROADMAP NAV")
navblock = "\n".join(nav)
y = MKDOCS.read_text()
if "BEGIN GENERATED ROADMAP NAV" in y:
    y = re.sub(r"      # BEGIN GENERATED ROADMAP NAV.*?      # END GENERATED ROADMAP NAV", navblock, y, flags=re.S)
else:
    y = y.rstrip() + "\n  - Roadmap:\n" + navblock + "\n"
MKDOCS.write_text(y)
print(f"generated roadmap: {total} tasks, {len(by_track)} tracks, {d} done")
